### ISSUE TITLE
integer out of range

### ISSUE THREAD

**Issue by papousek** [adaptive-learning/geography#119]
```
Internal Server Error: /flashcards/practice/
Traceback (most recent call last):
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/lazysignup/decorators.py", line 45, in wrapped
    return func(request, *args, **kwargs)
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/proso_flashcards/views.py", line 272, in practice
    saved_answers = _save_answer(request, answers)
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/proso_flashcards/views.py", line 350, in _save_answer
    db_answer.save()
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/django/db/models/base.py", line 616, in save_base
    self._save_parents(cls, using, update_fields)
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/django/db/models/base.py", line 641, in _save_parents
    self._save_table(cls=parent, using=using, update_fields=update_fields)
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/slepemapy.cz/virtualenv/geography-production-2/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
DataError: integer out of range


Request repr():
<WSGIRequest
path:/flashcards/practice/,
GET:<QueryDict: {u'all': [u'True'], u'stats': [u'True'], u'contexts': [u'["cz"]'], u'avoid': [u'[4526]'], u'limit': [u'1'], u'types': [u'["mountains"]'], u'categories': [u'[]']}>,
...
```

**Comment by papousek** [comment]
The problem here is that the client sends huge response time, e.g. 1436338029063.

**Comment by papousek** [comment]
It happens when user click on an option and immediately (before the next question is shown) clicks on "I don't know".
