### ISSUE TITLE
Deploy broken

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/geography#147]
I tried to do a deploy today. The site was running afterwards, but the changes were not applied (e.g. there should be a fix of feedback button width in Russian/German)

There was an error in later part of the deploy:
```
remote: Copying static/img/us-flags.png -> static/dist/img/us-flags.png
remote: Reading static/img/us-flags.png...OK
remote: Writing static/dist/img/us-flags.png...OK
remote: Copying static/img/world-outline.png -> static/dist/img/world-outline.png
remote: Reading static/img/world-outline.png...OK
remote: Writing static/dist/img/world-outline.png...OK
remote: Created 3 directories, copied 53 files
remote: 
remote: Done, but with warnings.
remote: Traceback (most recent call last):
remote:   File "/var/www/webs/outlinemaps-production/source/manage.py", line 10, in <module>
remote:     execute_from_command_line(sys.argv)
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
remote:     utility.execute()
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
remote:     django.setup()
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
remote:     apps.populate(settings.INSTALLED_APPS)
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
remote:     app_config = AppConfig.create(entry)
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/apps/config.py", line 116, in create
remote:     mod = import_module(mod_path)
remote:   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
remote:     __import__(name)
remote: ImportError: No module named social.apps.django_app
remote: Traceback (most recent call last):
remote:   File "/var/www/webs/outlinemaps-production/source/manage.py", line 10, in <module>
remote:     execute_from_command_line(sys.argv)
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
remote:     utility.execute()
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
remote:     django.setup()
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
remote:     apps.populate(settings.INSTALLED_APPS)
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
remote:     app_config = AppConfig.create(entry)
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/apps/config.py", line 116, in create
remote:     mod = import_module(mod_path)
remote:   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
remote:     __import__(name)
remote: ImportError: No module named social.apps.django_app
remote: Traceback (most recent call last):
remote:   File "/var/www/webs/outlinemaps-production/source/manage.py", line 10, in <module>
remote:     execute_from_command_line(sys.argv)
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
remote:     utility.execute()
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
remote:     django.setup()
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
remote:     apps.populate(settings.INSTALLED_APPS)
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
remote:     app_config = AppConfig.create(entry)
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/apps/config.py", line 116, in create
remote:     mod = import_module(mod_path)
remote:   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
remote:     __import__(name)
remote: ImportError: No module named social.apps.django_app
remote: Traceback (most recent call last):
remote:   File "/var/www/webs/outlinemaps-production/source/manage.py", line 10, in <module>
remote:     execute_from_command_line(sys.argv)
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
remote:     utility.execute()
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
remote:     django.setup()
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
remote:     apps.populate(settings.INSTALLED_APPS)
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
remote:     app_config = AppConfig.create(entry)
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/apps/config.py", line 116, in create
remote:     mod = import_module(mod_path)
remote:   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
remote:     __import__(name)
remote: ImportError: No module named social.apps.django_app
remote: Traceback (most recent call last):
remote:   File "/var/www/webs/outlinemaps-production/source/manage.py", line 10, in <module>
remote:     execute_from_command_line(sys.argv)
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
remote:     utility.execute()
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
remote:     django.setup()
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
remote:     apps.populate(settings.INSTALLED_APPS)
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
remote:     app_config = AppConfig.create(entry)
remote:   File "/usr/local/share/.virtualenvs/outlinemaps-production/lib/python2.7/site-packages/django/apps/config.py", line 116, in create
remote:     mod = import_module(mod_path)
remote:   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
remote:     __import__(name)
remote: ImportError: No module named social.apps.django_app
remote: Restarting project processes
remote: outlinemaps-production: stopped
remote: outlinemaps-production: started
remote: Maintenance off
```

**Comment by papousek** [comment]
Sorry, I've forgotten to tell you. Use `outlinemaps-production-2` instead of `outlinemaps-production` (and `outlinemaps-devel` instead of `outlinemaps-staging`, then devel.slepemapy.cz).
