### ISSUE TITLE
undefined context

### ISSUE THREAD

**Issue by papousek** [adaptive-learning/geography#159]
After migration on a new version of proso-apps:

```
77.104.214.246 - - [26/May/2016:16:40:52 +0200] "GET /models/to_practice/?all=True&filter=%5B%5B%22context%2Fundefined%22,%22category%2Fstate%22%5D%5D&stats=true HTTP/1.1" 500 38 "https://slepemapy.cz/overview/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
```

```
[2016-05-26 14:40:51,464] ERROR "Internal Server Error: /models/to_practice/"
Traceback (most recent call last):
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso/django/cache.py", line 25, in __cache_page_conditional
    return f(request, *args, **kwargs)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso_models/views.py", line 44, in to_practice
    item_ids = Item.objects.filter_all_reachable_leaves(practice_filter, get_language(request))
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso_models/models.py", line 467, in filter_all_reachable_leaves
    return self.filter_all_reachable_leaves_many([identifier_filter], language)[0]
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso_models/models.py", line 413, in filter_all_reachable_leaves_many
    translated = self.translate_identifiers(item_identifiers, language)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso_models/models.py", line 549, in translate_identifiers
    raise Exception("Can't translate the following identifiers: {}".format(set(identifiers) - set(result.keys())))
Exception: Can't translate the following identifiers: {'context/undefined'}
```

**Comment by slaweet** [comment]
The problem was that the request parameters were constructed from url after switching from /view/something to /overview
Fixed.
